trailingComma: "none"
useTabs: true
tabWidth: 4
printWidth: 140
semi: true
singleQuote: false
arrowParens: always
bracketSpacing: true
bracketSameLine: false
jsxSingleQuote: false
spaceBeforeFunctionParen: true
