trailingComma: "none"
tabWidth: 4
printWidth: 120
semi: true
singleQuote: false
arrowParens: always
bracketSpacing: true
bracketSameLine: false
jsxSingleQuote: false
useTabs: true
plugins: ["@trivago/prettier-plugin-sort-imports"]
importOrder:
    [
        "^react$",
        "chakra-ui",
        "<THIRD_PARTY_MODULES>",
        "interface",
        "context/",
        "config",
        "components/",
        "utils/",
        "services/",
        "enums/",
        "^../(.*)$",
        "types/",
        ".svg",
        "(?=./styles.module.scss)"
    ]
